<?php

namespace Database\Seeders;

use App\Models\Village;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AcehVillageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $villages = [
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Alue Bagok',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Alue Batee',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Alue Sundak',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Arongan',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Cot Buloh',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Cot Juru Mudi',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Cot Kumbang',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Drien Rampak',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Gunong Pulo',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Karang Hampa',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Keub',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Kubu',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Pante Mutia',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Panton Bahagia',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Panton Makmur',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Peulanteu',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Peuribu',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Rimba Langgeh',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Seneubok Lhong',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Seneubok Teungoh',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Simpang Peut',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Suak Bidok',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Suak le Beuso',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Suak Keumudai',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Teupin Peuraho',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Ujong Beusa',
            ],
            [
                'id_prov' => '1',
                'id_kota' => '1',
                'id_kec' => '1',
                'nama_kelurahan' => 'Ujong Simpang',
            ],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Alue Bakong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Alue Lhok"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Beurawang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Blang Sibeutong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Cot Keumuneng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Cot Lada"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Gunong Panah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Kuala Pling"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Kuta Padang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Layung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Liceh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Peulanteu"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Rambong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Seumuleng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Seuneubok Trap"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Suak Pangkat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '2', 'nama_kelurahan' => "Ulee Bang"],

            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Blang Beurandang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Drien Rampak"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Gampong Darat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Gampong Gampa"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Kampung Belakang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Kampung Pasir"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Kuta Padang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Lapang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Leuhan"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Padang Seurahet"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Panggong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Pasar Aceh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Rundeng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Seuneubok Trap"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Suak Indrapuri"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Suak Nie"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Suak Raya"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Suak Ribee"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Suak Sigadeng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Ujong Baroh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '3', 'nama_kelurahan' => "Ujung Kalak"],


            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Alue Lhee"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Alue Lhok"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Alue On"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Alue Peudeung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Alue Tampak"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Babah Meulaboh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Beureugang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Blang Dalam"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Blang Geunang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Batu Jaya"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Drien Caleue"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Kampong Mesjid"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Keude Aron"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Keude Tanjong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Keuramat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Marek"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Meunasah Ara"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Meunasah Buloh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Meunasah Gantung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Meunasah Rambot"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Meunasah Rayeuk"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Meunuang Tanjong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Muko"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Padang Mancang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Padang Sikabu"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Palimbungan"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Pasi Ara"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Pasi Jambu"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Pasi Jeumpa"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Pasi Kumbang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Pasi Meugat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Pasi Teungoh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Peunia"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Pucok Pungkie"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Pungkie"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Putim"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Puuk"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Sawang Tubei"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Simpang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Tanjong Bungong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Tanjong Meulaboh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Teladan"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Teupin Panah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '4', 'nama_kelurahan' => "Tumpok Ladang"],

            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Balee"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Bukit Jaya"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Buloh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Gunong Kleng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Langung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Mesjid Tuha"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Meureubo"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Pasi Aceh Baroh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Pasi Aceh Tunong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Pasi Mesjid"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Pasi Pinang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Paya Baro Ranto Panyang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Paya Peunaga"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Peunaga Cut Ujong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Peunaga Pasi"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Peunaga Rayeuk"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Pucok Redeup"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Pulo Tengoh Ranto Panyang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Ranto Panyang Barat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Ranto Panyang Timur"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Ranub Dong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Reudeup"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Sumber Batu"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Ujong Drien"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Ujong Tanjung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '5', 'nama_kelurahan' => "Ujong Tanah Darat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Alue Kumang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Babah Iseung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Babah Krueng Tep Lep"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Babah Lueng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Berdikari "],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Canggai"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Gunung Tarok"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Jambak"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Keutambang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Keude Suak Awe"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Krueng Beukah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Lango"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Lawet"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Lhok Guci"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Lhok Sari"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Manjeng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Meunaung Kinco"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Pante Ceureumen"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Pulo Tengah Manyang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Sawang Rambot"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Seumantok"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Seumara"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Sikundo"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Suak Awe"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '6', 'nama_kelurahan' => "Tegal Sari"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Antong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Babah Krueng Manggie"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Baro Paya"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Blang Balee"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Blang Teungoh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Cot Manggie"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Gampong Baro"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Gunung Mata Le"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Kuala Manye"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Lek Lek"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Manggie"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Meutulang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Mugo Cut"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Mugo Rayeuk"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Paya Baro Meuko"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Sibintang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Tamping"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Tuwi Buya"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '7', 'nama_kelurahan' => "Ujong Raja"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Alue Raya"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Cot Amun"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Cot Darat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Cot Lampise"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Cot Mesjid"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Cot Pluh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Cot Seulamat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Cot Seumeurreung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Deuah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Gampong Cot"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Gampong Ladang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Gampong Teungoh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Keureuseng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Krueng Tinggai"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Kuala Babon"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Leubok"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Leuken"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Lhok Bubon"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Mesjid Baro"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Pange"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Paya Lumpat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Pinem"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Pucok Leung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Rangkileh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Reusak"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Suak Geudeubang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Suak Pandan"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Suak Pante Breuh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Suak Seuke"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Suak Seumaseh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Suak Timah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '8', 'nama_kelurahan' => "Ujong Nga"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Drien Sibak"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Gaseu"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Geudong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Gleung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Gunong Buloh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Kajeung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Lancong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Lubok Beutong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Lueng Baro"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Pungki"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Ramitie"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Sakuy"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Sarah Perlak"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Sipot"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Tanoh Mirah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Tungkop "],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Tutut"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '9', 'nama_kelurahan' => "Tuwi Saya"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Alue Blang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Alue Panyang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Alue Sikaya"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Alue Sundak"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Aron Baroh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Aron Tunong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Bakat"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Blang Me"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Cot Keumundai"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Cot Lagan Bubon"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Cot Murong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Cot Situah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Darul Huda"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Drien Mangko"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Gempa Raya"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Glee Sibah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Gunong Rambong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Gunung Hampa"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Ie Itam Baroh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Ie Itam Tunong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Jawa"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Jawi"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Keuleumbah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Kuala Bhee"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Lueng Buloh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Lueng Jawa"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Lueng Tanon Tho"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Lueng Teungku Yah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Padang Jawa"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Panton"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Pasi Aceh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Pasi Ara Kuala Batee"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Pasi Birah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Pasi Lunak"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Pasi Pandan"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Paya Dua"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Paya Luah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Pulo le"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Ranto Panyang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Seumantok"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Suak Trieng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Teumarom"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '10', 'nama_kelurahan' => "Tingkeum Panyang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Alue Kemuning"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Alue Leuhop"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Alue Permen"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Blang Cot Mameh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Blang Cot Rubek"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Blang Luah Leuhop Mameh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Cot Lagan Leuhop Mameh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Cot Rambong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Ie Sayang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Karak"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Kulam Kaju"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Lhok Malee"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Lubuk Pasi Ara"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Lueng Baro"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Mon Pasong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Napai"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Pasi Jeut"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Pasi Malee"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Pasi Mali"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Pasi Panyang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Peuleukeung"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Simpang Keumarom"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Ule Pulo"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '11', 'nama_kelurahan' => "Ulei Pasi Ara"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Alue Bilie"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Alue Empeuk"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Alue Kuyun"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Alue Meuganda"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Alue Seuralen"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Blang Dalam"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Blang Luah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Blang Makmur"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Bukit Meugajah"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Cot Punti"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Gampong Baro"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Gampong Baro Woyla Timur"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Gunong Payang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Keubeu Capang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Lubuk Panyang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Pasi Ara Kuala Batee"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Pasi Janeng"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Paya Baro"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Paya Meugenderang"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Rambong"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Rambong Pinto"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Seuneubok Dalam"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Seuraduk"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Tangkeh"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Teumiket Ranom"],
            ['id_prov' => '1', 'id_kota' => '1', 'id_kec' => '12', 'nama_kelurahan' => "Tuwi Empeuk"],

            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Alue Dawah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Alue Jerjak"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Alue Penawa"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Blang Dalam"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Blang Raja"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Cot Seumantok"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Gunung Samarinda"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Ie Merah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Lhok Gayo"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Pantee Cermin"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Pantee Rakyat"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Rukoen Damee"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Simpang Gadeng"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '13', 'nama_kelurahan' => "Teladan Jaya"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Alum Anggota"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Babah Lhueng"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Baharu "],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Cot Jeurat"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Geulumpang Payong"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Gudang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Guhang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Kedai Paya"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Kedai Siblah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Kuta Bahagia"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Kuta Tinggi"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Kuta Tuha"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Lam Kuta"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Lhung Asan"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Lhung Tarok"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Mata le"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Meudang Ara"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Panton Raya"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Pasar Blang Pidie"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '14', 'nama_kelurahan' => "Seunaloh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Alue Rambot"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Alue Seulaseh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Alue Sungai Pinang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Asoe Nanggroe"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Baru"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Cot Mane"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Iku Lhung"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Jeumpa Barat"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Kuta Jeumpa"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Kuta Makmur"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Ladang Neubok"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '15', 'nama_kelurahan' => "Padang Geulumpang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Alue Padee"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Alue Pisang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Blang Makmur"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Blang Panyang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Drien Beurumbang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Gelanggang Gajah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Ie Mameh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Kampung Tengah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Keudee Baro"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Krueng Batee"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Krueng Panto"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Kuala Terubu"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Kuta Bahagia"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Lama Tuha"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Lhok Gajah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Lhung Geulumpang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Muka Blang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Padang Sikabu"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Panto Cut"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Pasar Kuta Bahagia"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '16', 'nama_kelurahan' => "Rumoh Panyang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Alue Rambot"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Cot Bak-U"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Geulanggang Batee"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Kayee Aceh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Kuta Paya"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Ladang Tuha I"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Ladang Tuha II"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Meunasah Sukon"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Meunasah Tengah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Meurandeh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Padang Keulele"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Suka Damai"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Tokoh II"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '17', 'nama_kelurahan' => "Ujung Tanah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Blang Manggeng"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Kedai "],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Ladang Panah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Lhok Pawoh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Lhok Puntol"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Lhung Barong"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Padang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Pante Cermin"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Pante Pirak"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Pante Raja"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Panton Makmur"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Paya"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Pusu Ingin Raya"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Sejahtera"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Seuneulop"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Tengah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Tokoh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '18', 'nama_kelurahan' => "Ujung Tanah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '19', 'nama_kelurahan' => "Lhang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '19', 'nama_kelurahan' => "Rambong"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '19', 'nama_kelurahan' => "Pisang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '19', 'nama_kelurahan' => "Ujung Tanah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '19', 'nama_kelurahan' => "Alue Dama"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '19', 'nama_kelurahan' => "Tangan-Tangan Cut"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '19', 'nama_kelurahan' => "Mon Mameh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '19', 'nama_kelurahan' => "Cinta Makmur"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '19', 'nama_kelurahan' => "Kuta Murni"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Baharu "],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Barat"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Blang Dalam"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Cot Mancang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Durian Jangek"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Durian Rampak"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Gadang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Geulima Jaya"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Kedai Palak Kerambil"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Kedai Susoh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Kepala Bandar"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Ladang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Lampoh Drien"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Meunasah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Padang Baru"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Padang Hilir"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Padang Panjang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Palak Hilir"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Palak Hulu"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Panjang Baru"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Pantai perak"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Pawoh"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Pinang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Pulau Kayu"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Rubek Meupayong"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Rumah Dua Lapis"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Rumah Panjang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Tangah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '20', 'nama_kelurahan' => "Ujung Padang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Adan"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Bineh Krueng"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Blang Padang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Drien Jalo"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Drien Kipah"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Gunung Cut"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Ie Lhop"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Kuta Bak Drien"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Mesjid"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Padang Bak Jeumpa"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Padang Bakjok"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Padang Kawa"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Pante Geulumpang"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Suak Labu"],
            ['id_prov' => '1', 'id_kota' => '2', 'id_kec' => '21', 'nama_kelurahan' => "Suak Nibung"],


            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Baet"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Blang Krueng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Cadek"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Cot Paya"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Kajhu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Klieng Cot Aron"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Klieng Meuria"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Labui"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Lam Asan"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Lam Ujong"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Lambada Lhok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Lampineung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '22', 'nama_kelurahan' => "Miruk Lam Reudeup"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Bueng Pageue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Bueng Sidom"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Bagie"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Geundreut"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Hoho"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Jambo"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Karieng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Leu'ot"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Madi"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Malem"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Mancang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Meulangen"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Mon Raya"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Nambak"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Puklat"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Rumpun"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Cot Sayun"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Data Makmur"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Eumpee Bata"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Gampong Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Kayee Kunyet"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Lam Siem"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Lam Me"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Meulayo"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Paya Ue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '23', 'nama_kelurahan' => "Teupin Batee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Bayu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Daroy Kameu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Denong"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Garot Geuceu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Geu Gajah"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Geundring"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Jeumpet Ajuen"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Kandang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Kuta Karang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lagang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lam Bheu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lam Blayang Manyang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lam Blang Trieng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lam Cot"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lam Kawee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lampasi Engking"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lampeuneun"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lampenunurut Gampong"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lampenunurut Ujong Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lamreung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lamsidaya"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lamsiteh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lamtheun"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Leu Ue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Leugeu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Lheu Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Pashie Butong"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Payaroh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Punie"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Tingkeum"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Ulee Lueng "],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '24', 'nama_kelurahan' => "Ulee Tui"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Biluy"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Blang Kiree"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Empee Trieng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Lam Baro Biluy"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Lam Batee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Lam Bleut"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Lam Kunyet"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Lam Sot"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Lam Tadok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Lhang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Mane Dayah"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Neusok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Teubaluy"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '25', 'nama_kelurahan' => "Turam"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Angan"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Barabung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Gampong Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Gampong Cot"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Krueng Kale"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lam Asan Klieng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lam Gawe"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lam Klat"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lam Peudaya"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lam Reh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lam Ujong Kileng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lambada Peukan"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lambaro Sukon"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lambiheu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lambiheu Siem"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lambitra"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lamduroy"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lamkeunung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lampuja"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lampuuk"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lamtipeung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Li Eue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Limpok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Miruk Taman"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Siem"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Suleue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Tanjung Deah"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Tanjung Selamat"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Tungkop"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '26', 'nama_kelurahan' => "Lam Asan Siem"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Aneuk Glee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Cot Kareung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Cureh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Empee Ara"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Groet Baro"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Groet Manyang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Grot Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Indrapuri"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Jruek Bak Kreh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Jruk Balee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Krueng Lamkreung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lam Ili Ganto"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lam Ili Mesjid"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lam Ili Teungoh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lam Leubok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lambeutong"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lambunot"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lamlueng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lampanah Baro"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lampanah Dayah"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lampanah Ranjo"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lampanah Teungoh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lampanah Tunong"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lampupok Baro"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lampupok Raya"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lamsiot"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lheu "],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Limo Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Limo Lamleuweung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Limo Mesjid"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Lingom"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Manggara"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Meunara"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Meusale Lhok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Mon Aleu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Mureu Baro"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Mureu Bueng Ue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Mureu Lamglumpang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Mureu Ule Titi"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Pasar Indrapuri"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Reukih Dayah"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Reukih Keupula"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Riting"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Seulangai"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Seuot Baroh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Seuot Tunong"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Seureumo"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Sihom Cot"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "SIhom Lhok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Sinyeu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Ulee Kareung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '27', 'nama_kelurahan' => "Ulee Ue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Bineh Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Jurong Peujeura"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lambaro Kaphee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lubok Batee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Meunasah Krueng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Meunasah Manyang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Pantee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Tanjong"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Ajee Cut"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Ajee Rayeuk"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Ateu Anggok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Ateuk Lung Le"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Bada"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Bakoy"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Bueng Sidom"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Bung Ceukok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Cot Alue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Cot Bada"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Cot Got"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Cot Karieng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Cot Madhi"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Cot Malem"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Cot Mentiwan"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Cot Suruy"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Dham Ceukok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Dham Ceukuk"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Dham Pulo"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Gampong Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Gani "],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Kayee Lee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lam Cot"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lam Ue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lambada "],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lamdaya"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lampreh Lamjampok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lampreh Lamteungoh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lamsinyeu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lamteungoh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lubok Gapuy"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Lubok Sukon"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Manyang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Meunasah Ajee"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Meunasah Baro"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Meunasah Dayah"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Meunasah Kalut"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Meunasah Manyet"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Meunasah Tutong"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Mukim Lubok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Paleuh Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Paleuh Pulo"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Pasi "],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Pasie Lubok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Reuloh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Santan Siron "],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Teubang Phui"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '28', 'nama_kelurahan' => "Ujong XII"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Bak Sukon"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Bandasafa"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Barih Lhok"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Bithak"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Bung Simek"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Cot Bayu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Gle Jai"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Ie Alang Dayah"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Ie Alang Lam Ghuy"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Ie Alang Lam Keureumeh"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Ie Alang Meuseujid"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Keumireu"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Keureuweung Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Keureuweung Krueng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Lam Alieng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Lam Beugak"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Lam Keupung"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Lam Leu'ot"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Lam Tui"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Lamkleeng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Lampakuk"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Lampoh Raja"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Lamsie"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Leupung Balue"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Leupung Bruek "],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Maheng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Pakuk"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Peukan Lampakuk"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Sigapang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Siron Blang"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Siron Krueng"],
            ['id_prov' => '1', 'id_kota' => '3', 'id_kec' => '29', 'nama_kelurahan' => "Tutue"],


        ];
        foreach ($villages as $village) {
            Village::factory()->create($village);
        }
    }
}